services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/financialaccounting
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
      - ./exports:/app/exports

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: financialaccounting
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d financialaccounting" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: